#!/bin/bash

# 📸 MoveEasy Screenshot Capture Helper
# Interactive guide for taking Play Store screenshots

echo "🎯 MoveEasy Screenshot Capture Guide"
echo "======================================"
echo ""
echo "Your app is running at: http://localhost:8080"
echo "Screenshots will be saved to: ./play-store-screenshots/"
echo ""

# Create screenshots directory if it doesn't exist
mkdir -p ./play-store-screenshots

echo "📱 STEP-BY-STEP SCREENSHOT GUIDE"
echo "================================"
echo ""

echo "🔧 SETUP (Do this first):"
echo "1. Open Chrome or Firefox"
echo "2. Navigate to: http://localhost:8080"
echo "3. Press F12 to open Developer Tools"
echo "4. Click the device toolbar icon (📱)"
echo "5. Select 'iPhone 12 Pro' or 'Pixel 5' from dropdown"
echo "6. Set zoom to 100%"
echo ""

read -p "✅ Ready? Press Enter when you've completed the setup..."

echo ""
echo "📸 SCREENSHOT 1: HERO LANDING PAGE"
echo "================================="
echo "📍 URL: http://localhost:8080/"
echo "🎯 What to capture:"
echo "   - Hero section with moving truck image"
echo "   - 'Find the Best Moving Services in Kenya' headline"
echo "   - Navigation bar"
echo "   - Quote form at the top"
echo ""
echo "📱 Instructions:"
echo "   1. Make sure you're on the home page"
echo "   2. Scroll to the very top if needed"
echo "   3. Right-click in the mobile viewport"
echo "   4. Select 'Capture screenshot' or use Ctrl+Shift+P → 'Capture screenshot'"
echo "   5. Save as: ./play-store-screenshots/01-hero-landing.png"
echo ""

read -p "📸 Take Screenshot 1 now, then press Enter to continue..."

echo ""
echo "📸 SCREENSHOT 2: QUOTE FORM - EMPTY STATE"
echo "========================================"
echo "📍 URL: http://localhost:8080/"
echo "🎯 What to capture:"
echo "   - Clean quote form interface"
echo "   - From/To location fields"
echo "   - Property type dropdown"
echo "   - Date picker"
echo "   - Get Quote button"
echo ""
echo "📱 Instructions:"
echo "   1. Scroll down to focus on the quote form"
echo "   2. Make sure form is empty and clean"
echo "   3. Take screenshot of the form area"
echo "   4. Save as: ./play-store-screenshots/02-quote-form-empty.png"
echo ""

read -p "📸 Take Screenshot 2 now, then press Enter to continue..."

echo ""
echo "📸 SCREENSHOT 3: QUOTE FORM - FILLED EXAMPLE"
echo "==========================================="
echo "📍 URL: http://localhost:8080/"
echo "🎯 What to capture:"
echo "   - Form filled with realistic example data"
echo "   - Shows ease of use and functionality"
echo ""
echo "📱 Instructions:"
echo "   1. Fill the form with this example data:"
echo "      - From: 'Nairobi CBD, Kenya'"
echo "      - To: 'Mombasa, Kenya'"
echo "      - Property Type: '3 Bedroom House'"
echo "      - Date: Pick a future date"
echo "   2. DON'T submit yet!"
echo "   3. Take screenshot showing filled form"
echo "   4. Save as: ./play-store-screenshots/03-quote-form-filled.png"
echo ""

read -p "📸 Fill form and take Screenshot 3, then press Enter to continue..."

echo ""
echo "📸 SCREENSHOT 4: CONTACT FORM / NEXT STEP"
echo "========================================"
echo "📍 URL: http://localhost:8080/"
echo "🎯 What to capture:"
echo "   - Contact information form"
echo "   - Professional form progression"
echo "   - Next step in the user journey"
echo ""
echo "📱 Instructions:"
echo "   1. Now click 'Get Quote' to submit the form"
echo "   2. Wait for the contact form to appear"
echo "   3. Take screenshot of the contact form"
echo "   4. Save as: ./play-store-screenshots/04-contact-form.png"
echo ""

read -p "📸 Submit form and take Screenshot 4, then press Enter to continue..."

echo ""
echo "📸 SCREENSHOT 5: RESULTS / SUCCESS STATE"
echo "======================================"
echo "📍 URL: http://localhost:8080/"
echo "🎯 What to capture:"
echo "   - Quote results or success message"
echo "   - Professional results display"
echo "   - Value delivery shown"
echo ""
echo "📱 Instructions:"
echo "   1. Fill the contact form with:"
echo "      - Name: 'John Doe'"
echo "      - Email: 'john@example.com'"
echo "      - Phone: '+254712345678'"
echo "   2. Submit the contact form"
echo "   3. Wait for results/success page"
echo "   4. Take screenshot of the results"
echo "   5. Save as: ./play-store-screenshots/05-results.png"
echo ""

read -p "📸 Complete the flow and take Screenshot 5, then press Enter to continue..."

echo ""
echo "🔄 OPTIONAL: TABLET SCREENSHOTS"
echo "=============================="
echo "📍 For better Play Store presentation (optional but recommended)"
echo ""
echo "📱 Instructions:"
echo "   1. In Developer Tools, change device to 'iPad Air' or 'iPad Pro'"
echo "   2. Repeat screenshots 1-3 for tablet layout"
echo "   3. Save with '-tablet' suffix:"
echo "      - 01-hero-landing-tablet.png"
echo "      - 02-quote-form-empty-tablet.png"
echo "      - 03-quote-form-filled-tablet.png"
echo ""

read -p "🔄 Take tablet screenshots if desired, then press Enter to continue..."

echo ""
echo "✅ SCREENSHOT QUALITY CHECK"
echo "=========================="
echo "📋 Verify your screenshots have:"
echo "   □ Clear, readable text"
echo "   □ Professional appearance"
echo "   □ No loading states or errors"
echo "   □ Consistent branding"
echo "   □ Mobile-friendly layout"
echo "   □ Good contrast and visibility"
echo ""

echo "📁 Your screenshots should be saved in:"
echo "   ./play-store-screenshots/"
echo ""

read -p "🔍 Check your screenshots now, then press Enter to finish..."

echo ""
echo "🎉 SCREENSHOT CAPTURE COMPLETE!"
echo "=============================="
echo ""
echo "📸 You should now have:"
echo "   ✅ 01-hero-landing.png"
echo "   ✅ 02-quote-form-empty.png"
echo "   ✅ 03-quote-form-filled.png"
echo "   ✅ 04-contact-form.png"
echo "   ✅ 05-results.png"
echo "   📱 Optional tablet versions"
echo ""

echo "🚀 NEXT STEPS:"
echo "   1. Review all screenshots for quality"
echo "   2. Edit/enhance if needed"
echo "   3. Upload to Google Play Console"
echo "   4. Complete store listing with provided content"
echo ""

echo "📋 Files ready for Play Store:"
echo "   📱 Screenshots: ./play-store-screenshots/"
echo "   🎨 App icon: ./play-store-icon.png"
echo "   🖼️ Feature graphic: ./feature-graphic.png"
echo "   📦 AAB file: ./android/app/build/outputs/bundle/release/app-release.aab"
echo "   📄 Store listing: ./PLAY_STORE_LISTING.md"
echo ""

echo "🎯 Your app is ready for Play Store submission!"