// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eyfvvtpbttmsqubxglyg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV5ZnZ2dHBidHRtc3F1YnhnbHlnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3NTUwNjEsImV4cCI6MjA2NTMzMTA2MX0.HkNO1f1u7lSO_7jVsicQQp-bueOESh_8GxCB7kTYOPk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});